10개의 양수로 된 간단한 numpy 배열 만들기


In [2]:
import numpy as np

numbers = np.array(range(1,11),copy = True)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ones() -> 1 zeros() -> 0, empty() -> 아직 생성되지 않은 엔트리로 구성

In [3]:
#아직 생성되지 않은 엔트리로 구성된 배열을 1로 채움
ones = np.ones([3,4])
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
#아직 생성되지 않은 엔트리로 구성된 배열을 0으로 채움

zeros = np.zeros([2,4],dtype=np.float64)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
#아직 생성되지 않은 엔트리로 구성된 배열

empty = np.empty([2,4],dtype=np.float64)
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

데이터 확인하기

In [8]:
ones.shape

(3, 4)

In [9]:
ones.ndim

2

In [10]:
ones.dtype

dtype('float64')

In [11]:
numbers.dtype

dtype('int64')

arange(start,stop,step,dtype) 일정 간격으로 배열 생성하는 함수

In [12]:
np_number = np.arange(2,5,0.25)
np_number

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75])

astype(dtype, casting="unsafe", copy=True) 아이템의 타입 변경해 주는 함수


In [14]:
np_number = np_number.astype(np.int)
np_number.dtype

dtype('int64')

reshape(d0, d1, ...) 대상 배열의 모양을 바꿔주는 함수


In [16]:
# 몇 가지 S&P 주식 기호들
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
sap #U4 는 4글자 유니코드


array(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ATVI', 'ADBE', 'ADT'],
      dtype='<U4')

In [18]:
sap.shape

(8,)

In [22]:
sap2d = sap.reshape(2,4)
sap2d

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [27]:
# 기존 배열과 새로운 배열의 아이템의 개수는 항상 동일 해야 함
# numpy 보존의 법칙 성립

sap3d = sap.reshape(2,2,2)
sap3d

array([[['MMM', 'ABT'],
        ['ABBV', 'ACN']],

       [['ACE', 'ATVI'],
        ['ADBE', 'ADT']]], dtype='<U4')

데이터 클리닝(data cleaning)을 위해 사용 되는 boolean indexing


In [30]:
#절대 음수 값이 와서는 안되는 데이터셋

dirty = np.array([9,4,1,-0.01,-0.02,-0.001])

whos_dirty = dirty < 0 
whos_dirty

array([False, False, False,  True,  True,  True])

In [32]:
dirty[whos_dirty] = 0 #모든 음수값을 0으로 바꿈
dirty 

array([9., 4., 1., 0., 0., 0.])

논리 연산자 | or, & and, - not 결합하여 boolean indexing 사용



In [34]:
llnear = np.arange(-1,1.1,0.2)
llnear

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01,  1.00000000e+00])

In [36]:
# -0.5 ~ 0.5 사이의 값만 -> 0으로 변경하고 싶음

whos_llnear = (llnear <=0.5) & (llnear>= -0.5)
whos_llnear

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False])

In [38]:
llnear[whos_llnear] = 0
llnear

array([-1. , -0.8, -0.6,  0. ,  0. ,  0. ,  0. ,  0. ,  0.6,  0.8,  1. ])

스마트 인덱싱

In [40]:
# S&P 리스트에서 두번째, 세번째, 마지막 주식 기호를 추출

sap[[1,2,-1]]

array(['ABT', 'ABBV', 'ADT'], dtype='<U4')

In [41]:
sap2d 

array([['MMM', 'ABT', 'ABBV', 'ACN'],
       ['ACE', 'ATVI', 'ADBE', 'ADT']], dtype='<U4')

In [44]:
sap2d[:,[1]]

array([['ABT'],
       ['ATVI']], dtype='<U4')

In [46]:
sap2d[:,1]

array(['ABT', 'ATVI'], dtype='<U4')

차원만 같다면 numpy에서는 사칙연산 가능 (그낭 더하기) -> 브로드캐스팅


In [50]:
a= np.arange(4)
b = np.arange(1,5)

print(a)
print(b)

[0 1 2 3]
[1 2 3 4]


In [52]:
a+b

array([1, 3, 5, 7])

In [55]:
a*5

array([ 0,  5, 10, 15])

In [61]:
noise = np.eye(4) + 0.01 * np.random.random([4,4])
noise

array([[1.00452553, 0.00878287, 0.00587531, 0.00802159],
       [0.00656822, 1.00079562, 0.00566178, 0.00734844],
       [0.00335644, 0.00677148, 1.00363367, 0.00612658],
       [0.0095616 , 0.00531181, 0.00919412, 1.00702811]])