In [1]:
import numpy as np

In [2]:
array1=np.array([2,3,5,7,11,13,17,19,23,29])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [4]:
array1>4 #4보다 큰 수

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
booleans=np.array([True,True,True,True,False,False,True])

In [10]:
np.where(booleans)

(array([0, 1, 2, 3, 6], dtype=int64),)

In [11]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [12]:
np.where(array1 >4 )

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)