In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,-1],[1,1,-3]])

In [5]:
b=np.array([[3,2,-2],[-1,2,1]])

In [6]:
a+b     #-3

array([[ 4,  4, -3],
       [ 0,  3, -2]])

In [21]:
b=([[3],[1],[2]])

In [20]:
a.dot(b) #3

array([[ 3,  5],
       [-2,  6]])

In [18]:
b=np.array([[3,2],[1,1],[2,-1]])

In [19]:
a.dot(b) #5

array([[ 3,  5],
       [-2,  6]])