In [2]:
import numpy


In [4]:
array1= numpy.array([1,2,3,2,5,75,12,3])

In [6]:
array1

array([ 1,  2,  3,  2,  5, 75, 12,  3])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array1.shape

(8,)

In [11]:
array2=numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [12]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
type(array2)

numpy.ndarray

In [15]:
array2.shape

(3, 4)

In [16]:
array1.size

8

In [17]:
array2.size

12

In [43]:

array1 = numpy.full(6,0)
array2=numpy.random.random(6)

In [44]:
print(array1)
print(array2)

[0 0 0 0 0 0]
[0.53398396 0.12143967 0.80177124 0.20791283 0.33035337 0.72191018]
