In [1]:
import numpy as np

In [2]:
array1 = np.array([2,3,5,7,9,11,13,15,17])

In [3]:
array1

array([ 2,  3,  5,  7,  9, 11, 13, 15, 17])

In [5]:
array1[0]

2

In [6]:
array1[5]

11

In [7]:
array1[-1]

17

In [9]:
array1[[1,3,7]]

array([ 3,  7, 15])

In [10]:
array2=np.array([2,1,3])

In [11]:
array1[array2]

array([5, 3, 7])

In [12]:
array1[2:7]

array([ 5,  7,  9, 11, 13])

In [13]:
array1[2:6:3] #2~6번까지 숫자 3개 건너뛰기

array([ 5, 11])